env:
  BRANCH: ${{ (github.ref_name) }}
  CLASSES: ${{ (github.event.inputs.CLASSES_TO_EXECUTE_INPUT) }}
  COMMIT_HASH: ${{ (github.sha) }}
  LOCATION: ${{ secrets.LOCATION }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  PULL_REQUEST_NUMBER: ${{ (github.event.inputs.PULL_REQUEST_NUMBER_INPUT) }}
  QUEUE_ID: ${{ secrets.QUEUE_ID }}
  SERVICE_ACCOUNT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
  WORKFLOW_URL: ${{ secrets.WORKFLOW_URL }}
jobs:
  execute_workflow:
    if: github.repository == 'graphql-java/graphql-java'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-node@v4
      with:
        node-version: '14'
    - continue-on-error: true
      run: npm install --prefix .github/workflows
    - continue-on-error: true
      if: ${{ github.event_name == 'workflow_dispatch' }}
      name: Update COMMIT_HASH
      run: echo "COMMIT_HASH=${{ (github.event.inputs.COMMIT_HASH_INPUT) }} " >> $GITHUB_ENV
    - continue-on-error: true
      if: ${{ github.event_name == 'workflow_dispatch' }}
      name: Update BRANCH
      run: echo "BRANCH=${{ (github.event.inputs.BRANCH_INPUT) }} " >> $GITHUB_ENV
    - continue-on-error: true
      id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2.1.3
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    - continue-on-error: true
      name: Execute JS script
      run: node .github/workflows/create_job.js
name: invoke_test_runner
on:
  repository_dispatch:
    types: trigger-ga___invoke_test_runner.yml
