jobs:
  buildAndTest:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: '11'
    - continue-on-error: true
      name: build and test
      run: ./gradlew assemble && ./gradlew check --info --stacktrace
name: Pull Request Build
on:
  repository_dispatch:
    types: trigger-ga___pull_request.yml
