jobs:
  close-pending:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        close-issue-message: 'Hello, as this issue has been inactive for 90 days,
          we''re closing the issue. If you would like to resume the discussion, please
          create a new issue.

          '
        close-pr-message: 'Hello, as this pull request has been inactive for 90 days,
          we''re closing this pull request. We always welcome contributions, and if
          you would like to continue, please open a new pull request.

          '
        days-before-issue-close: 30
        days-before-pr-close: 30
        days-before-stale: 60
        exempt-all-milestones: true
        exempt-issue-labels: keep-open
        exempt-pr-labels: keep-open
        stale-issue-message: 'Hello, this issue has been inactive for 60 days, so
          we''re marking it as stale. If you would like to continue this discussion,
          please comment within the next 30 days or we''ll close the issue.

          '
        stale-pr-message: 'Hello, this pull request has been inactive for 60 days,
          so we''re marking it as stale. If you would like to continue working on
          this pull request, please make an update within the next 30 days, or we''ll
          close the pull request.

          '
name: Close stale issues and PRs
on:
  repository_dispatch:
    types: trigger-ga___stale-pr-issue.yml
permissions:
  actions: write
  issues: write
  pull-requests: write
